name: lelan
channels:
  - defaults
dependencies:
  - asttokens
  - backcall
  - blas
  - brotli
  - brotli-bin
  - ca-certificates
  - comm
  - contourpy
  - cycler
  - cyrus-sasl
  - cython
  - dbus
  - debugpy
  - decorator
  - executing
  - expat
  - fontconfig
  - fonttools
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - importlib-metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcups
  - libdeflate
  - libedit
  - libffi
  - libgcc-ng
  - libgomp
  - libllvm14
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - mysql
  - ncurses
  - nest-asyncio
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - ply
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - pyparsing
  - pyqt5-sip
  - python-dateutil
  - pyzmq
  - qt-main
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - stack_data
  - tk
  - tomli
  - tornado
  - traitlets
  - typing_extensions
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - certifi
    - clip
    - clu
    - cuda-python
    - diffusers
    - efficientnet-pytorch
    - einops
    - filelock
    - fsspec
    - ftfy
    - h5py
    - huggingface-hub
    - lmdb
    - lvis
    - mpmath
    - networkx
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - opencv-python
    - ott-jax
    - positional-encodings
    - prettytable
    - promise
    - pycocotools
    - pytube
    - pytubefix
    - pyyaml
    - regex
    - shortuuid
    - sympy
    - torch
    - torchvision
    - tqdm
    - triton
    - vit-pytorch
    - wandb
    - warmup-scheduler
    - wcwidth
